image:
  repository: "sonatype/nexus3"
  # tag is taken from Chart.appVersion if not specified
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

persistence:
  enabled: true
  # Use default storageClass or specify custom one
  storageClass: ${storage_class}
  accessMode: ReadWriteOnce
  size: 8Gi # update for your needs
  # Specify mount paths for Nexus data
  mountPath: /nexus-data

nexus:
  securityInitialPassword: ${admin_pass} # Replace with your admin password from env vars or secret manager
  master: "https://${master}" # Replace with your remote repository URL
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

server:
  name: Server
  replicas: 1
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi

  ingress:
    enabled: true
    className: alb
    port: 8081
    annotations:
      #alb.ingress.kubernetes.io/scheme: "internal"
      #alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      #alb.ingress.kubernetes.io/target-type: ip
      #alb.ingress.kubernetes.io/backend-protocol: HTTPS
      #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:id
      #alb.ingress.kubernetes.io/group.name: nexus
    hosts:
      - host: devnexus.local
        paths:
          - path: /
            pathType: Prefix

  spec:
    ingressClassName: alb
    rules:
      - host: "devnexus.aws"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: nexus-proxy
                  port:
                    number: 8081
