apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-script
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    # Wait for Nexus to be ready
    until curl -sf http://{{ .Release.Name }}:8081/service/rest/v1/status; do
      echo "Waiting for Nexus to be ready..."
      sleep 10
    done
    echo Wait for a bit
    sleep 10
    echo =-=-=-=-=-=-=-= Allow anonymous access for pulling =-=-=-=-=-=-=-=
    curl -X 'PUT' -u admin:{{ .Values.nexus.securityInitialPassword }} 'http://{{ .Release.Name }}:8081/service/rest/v1/security/anonymous' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{ "enabled": true, "userId": "anonymous", "realmName": "NexusAuthenticatingRealm"}'
    echo =-=-=-=-=-=-=-= Anonymous access for pulling allowed, now try to 'EULA' accept =-=-=-=-=-=-=-= 
    curl -X 'POST' -v -s -u admin:{{ .Values.nexus.securityInitialPassword}} 'http://{{ .Release.Name }}:8081/service/rest/v1/system/eula' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"accepted": true, "disclaimer": "Use of Sonatype Nexus Repository - Community Edition is governed by the End User License Agreement at https://links.sonatype.com/products/nxrm/ce-eula. By returning the value from ‘accepted:false’ to ‘accepted:true’, you acknowledge that you have read and agree to the End User License Agreement at https://links.sonatype.com/products/nxrm/ce-eula."}'
    echo EULA accepted
    echo Create raw proxy repository
    curl -v -s -X POST "http://{{ .Release.Name }}:8081/service/rest/v1/repositories/raw/proxy" \
      -u "admin:{{ .Values.nexus.securityInitialPassword  }}" \
      -H "accept: application/json" \
      -H "Content-Type: application/json" \
    -d '{
      "name": "raw-proxy",
      "online": true,
      "storage": {
        "blobStoreName": "default",
        "strictContentTypeValidation": true
      },
      "cleanup": {
        "policyNames": [
          "string"
        ]
      },
      "proxy": {
        "remoteUrl": "{{ .Values.nexus.master }}",
        "contentMaxAge": 1440,
        "metadataMaxAge": 1440
      },
      "negativeCache": {
        "enabled": true,
        "timeToLive": 1440
      },
      "httpClient": {
        "blocked": false,
        "autoBlock": true,
        "connection": {
          "retries": 0,
          "userAgentSuffix": "string",
          "timeout": 60,
          "enableCircularRedirects": false,
          "enableCookies": false,
          "useTrustStore": false
        },
        "authentication": {
          "type": "username",
          "username": "string",
          "password": "string",
          "ntlmHost": "string",
          "ntlmDomain": "string",
          "bearerToken": "string"
        }
      },
      "routingRule": "string",
      "replication": {
        "preemptivePullEnabled": false,
        "assetPathRegex": "string"
      },
      "raw": {
        "contentDisposition": "ATTACHMENT"
      }
    }'
    echo "Initialization script completed."
